CREATE TABLE FORMATS(
    ID NUMBER,
    FORMATS NVARCHAR2(50)
);


CREATE TABLE STORAGES(
    ID NUMBER ,
    CONSTRAINT STORAGE_PK PRIMARY KEY(ID),
    STORAGE_COUNTRY NVARCHAR2(50),
    STORAGE_MAX_SIZE NUMBER
);


CREATE TABLE FILES(
    ID NUMBER ,
    CONSTRAINT FILES_PK PRIMARY KEY(ID),
    NAME NVARCHAR2(50),
    FORMAT NVARCHAR2(20),
    FILE_SIZE NUMBER,
    STORAGE_ID NUMBER,
    CONSTRAINT STORAGE_FK FOREIGN KEY(STORAGE_ID)
    REFERENCES STORAGES(ID)
);


CREATE SEQUENCE FILESQ MINVALUE 1 MAXVALUE 100 START WITH 1 INCREMENT BY 1 ;

CREATE SEQUENCE STORAGESQ MINVALUE 1 MAXVALUE 100 START WITH 1 INCREMENT BY 1 ;